version: "3.9"
services:
  radar-dev:
    container_name: 'radar-dev'
    hostname: 'radar-dev'
    image: 'radar/melodic:develop'
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    ports:
      - "8888:8888"
      - "8808:8808/udp"
    volumes:
      - .:/root/radar
    tty: true
    working_dir: /root/
